### ISSUE TITLE
sharedWorkflowUtils.js seems to be an old version

### ISSUE THREAD

**Issue by Octav14n** [ImDarkTom/ComfyUIMini#1]
I get errors in "src/public/js/modules/sharedWorkflowUtils.js", in the function "renderAllInputs", it accesses members of "workflowJson" that the server does not send (for example: it iterates over workflowJson, instead of workflowJson.nodes)
after fixing this, it tries to find "_comfyuimini_meta" which isn't send by the server. Is there a newer Version available?

**Comment by ImDarkTom** [comment]
This is because I intended users to import workflows using the "Save (API Format)" option which uses less space by cutting out unnecesary data such as node position, size, etc. I'll release an update that clarifies on this as I've seen multiple users mention not being able to properly import workflows.

**Comment by ImDarkTom** [comment]
This has been clarified in the latest release. Users will now get a popup when trying to import non-API formatted workflows along with a guide on how to enable the option.
