### ISSUE TITLE
Getting this error.. Flux STOIQ 4 step 8fp.json does not have any attached ComfyUIMini metadata, skipping...

### ISSUE THREAD

**Issue by jdc4429** [ImDarkTom/ComfyUIMini#7]
Do you not have metadata included for Flux models??? 
[WARN] Flux STOIQ 4 step 8fp.json does not have any attached ComfyUIMini metadata, skipping...
[2024-09-23 19:38:45] [WARN] NEW SDXL Lightning 8 step API.json does not have any attached ComfyUIMini metadata, skipping...

I don't understand.. it does not seem to save after filling in all the fields that say 'Select' why do you have to do that??? The interface is terrible and I can't even figure out how to run a workflow! Refreshing models does nothing.

C:\ComfyUIMini>node .
[2024-09-23 19:38:45] [INFO] Found 2 workflows in the workflow folder.
[2024-09-23 19:38:45] [WARN] Flux STOIQ 4 step 8fp.json does not have any attached ComfyUIMini metadata, skipping...
[2024-09-23 19:38:45] [WARN] NEW SDXL Lightning 8 step API.json does not have any attached ComfyUIMini metadata, skipping...
[2024-09-23 19:38:45] [INFO] Loaded 5 model types.
[2024-09-23 19:38:45] [SUCCESS] Running on http://10.0.0.109:3000
[2024-09-23 19:38:45] [SUCCESS] 200: ComfyUI is running.
[2024-09-23 19:42:51] [INFO] Loaded 5 model types.
[2024-09-23 19:42:59] [INFO] Loaded 5 model types.
[2024-09-23 19:43:36] [INFO] Loaded 5 model types.

**Comment by ImDarkTom** [comment]
> Do you not have metadata included for Flux models???
> [WARN] Flux STOIQ 4 step 8fp.json does not have any attached ComfyUIMini metadata, skipping...
 
This specific warning is when you try to add a workflow directly into the folder without first running it through the import page in the UI, this is necessary as otherwise it will be unable to determine what type of inputs (text, integer, model selection, etc.) each node has. It does not have anything to do with Flux compatibility as Flux is just another checkpoint model.
 
> I don't understand.. it does not seem to save after filling in all the fields that say 'Select' why do you have to do that??? 
 
This may have been an oversight on my part, when it says select it means that the input type chosen for that input is 'select from a list of models (such as checkpoints, vae, etc)'. This does not mean that you need to select Text, Integer or Float, because Select is already one of the input types. This will be clarified in a soon release.

You should be able to save the workflow by either pressing the save to browser button (which saves it to localStorage and lets you run it without download), or by downloading it and dropping that into the /workflows/ folder within the UI, at which point you will be able to access and run it through the UI.
 
> The interface is terrible and I can't even figure out how to run a workflow! Refreshing models does nothing.
 
The interface is primarily designed for mobile devices so there may be scaling issues when viewing on a desktop. The UI is still being worked on but currently I am busy with the main functionality before working on making the UI better.


Please be aware that I am the sole person working on this project, so some features may not be polished to the standard that other projects such as the main ComfyUI are, so please be patient while I try to address any issues that people may have.

**Comment by ImDarkTom** [comment]
Automatic metadata generation has been added in the latest release, this should let workflows run without needing to manually import them.
